Fix issue #120
launchdarkly/go-client pull request #121
Opened 2018-06-08 11:49 UTC by guilherme-santos

2018-06-08 15:58 UTC, ashanbrown commented
@guilherme-santos Thanks for your contribution.  My understanding is that you'd like to return control to your app immediately when the response is 401 (unauthorized due to a bad key) rather than waiting for the full initialization timeout.  Is that correct?  That sounds like a reasonable expectation.  It is possible to implement this without changing the public interface?  There is a related change we are also considering which involves checking initialization success after we complete our initialization attempt and introducing a separate error response indicating that we failed to initialize immediately.  That might be relevant here. Thanks.

2018-06-08 16:09 UTC, guilherme-santos commented
Exactly this that I'd like. I'll try to do something without break the public API.

2018-06-09 11:05 UTC, guilherme-santos commented
@ashanbrown I fixed to not break the public api, but the return is not the real error instead will be only `Error initializing LaunchDarkly`, IMO we should refactor to return the proper error but as you're already logging I think is fine for while, can you review it?

2018-06-09 14:21 UTC, ashanbrown requested changes
Thank you for the fantastic updates and all the additional tests.  I have a few comments for changes that I hope you can make it and then it should be ready to merge.

2018-06-09 14:21 UTC, ashanbrown commented on streaming.go
> +				close(closeWhenReady)
I'm concerned that we might try to call `close` multiple times on this channel.  I think we can avoid this by using `sync.Once` to ensure this only happens once.  We could define:

```
var closer sync.Once
closeOnce := func() {
   closer.Do(func() {
      close(closeWhenReady)
   })
}
```
at the beginning of the method and then call `closeOnce()`

In retrospect, I won't be using a channel that works based on closing again as part of an interface but at this point the interface is out there.  ;)

2018-06-09 14:21 UTC, ashanbrown commented on ldclient.go
> +				return nil, ErrInitializationFailed
We still need to return the client here instead of `nil`.  It is our policy to always return the client, because the client is still expected to serve default values to the application, even if it fails to connect to the service.  We are definitely at fault for not making this clear in our test suite.

2018-06-09 14:21 UTC, ashanbrown commented on ldclient.go
> +				return nil, ErrInitializationTimeout
Again, let's return the client.

2018-06-09 15:38 UTC, guilherme-santos commented on streaming.go
> +				close(closeWhenReady)
Actually, I thought the same, but in the end, I had the impression that will not happen. But for sure that way is the safer to go.

2018-06-09 15:38 UTC, guilherme-santos commented
Changes made!

2018-06-11 21:32 UTC, guilherme-santos commented
@ashanbrown can you check again?

2018-06-11 22:28 UTC, ashanbrown commented
@guilherme-santos I created PR https://github.com/guilherme-santos/go-client/pull/1 against your original PR which has some fixes I think we need.  If you can merge that, I can test our our combined changes.  Thanks.

2018-06-13 05:37 UTC, guilherme-santos commented
Hey @ashanbrown I think now we're ready to go! :)

2018-06-13 14:05 UTC, merged

2018-06-13 14:14 UTC, ashanbrown commented
Thank you!